### ISSUE TITLE
Images take looong time to load

### ISSUE THREAD

**Issue by highoncarbs** [astronomersiva/siva.dev#66]
Vanakkam! A big fan of your blog . I just wanted to point out that images take an awful lot of time to load on your blog. Everything else feels real fast and smooth , except for the images.

Cheers!

**Comment by astronomersiva** [comment]
Vanakkam @highoncarbs!

Apologies for missing out on this issue. This was a result of one of my experiments not performing as much as I expected due to frequent CDN misses. I had [rolled it back](https://github.com/astronomersiva/siva.dev/commit/9f83f928e4ff245e1e1fd98ff7c8edebfc49d806) mid-November so this should no longer be a problem. Please let me know if you are still facing this.

Really appreciate you taking the time to bring this to my notice, apologies again for not responding earlier 🙏

**Comment by highoncarbs** [comment]
Yup, works well now.
Cheers!
